version: '3.8'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ofitec
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:16
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    ports:
      - "8069:8069"
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
    restart: unless-stopped
    command: ["odoo", "--init", "base,web,bus,mail,project,account", "--addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons", "--db_host=db", "--db_user=odoo", "--db_password=odoo"]

volumes:
  db_data:
  odoo_data:
