name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-ai.txt
        pip install flake8 pytest odoo-test-helper
    
    - name: Lint with flake8
      run: |
        flake8 custom_addons/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 custom_addons/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run Odoo tests
      run: |
        # Configurar base de datos de prueba
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo -u postgres createuser --createdb --superuser runner
        createdb ofitec_test
        
        # Instalar módulos y ejecutar pruebas
        python -m odoo --config=config/odoo.conf --test-enable --test-tags=ofitec --database=ofitec_test --stop-after-init
    
    - name: Check Docker Compose
      run: |
        docker-compose config --quiet
    
    - name: Run integration tests
      run: |
        python test_integration_fase2.py
        python test_dashboard_executive.py
        python test_ml.py
